name: GrapplingHook
author: Brandon Curtis
description: A simple grappling hook plugin.
version: ${project.version}
main: com.caved_in.grapplinghook.GrapplingHook
depend: [Commons]
permissions:
    grapplinghook.command.give:
        description: Allows player to use command /gh give
        default: op
    grapplinghook.player.nocooldown:
        description: Player ignores grapple cooldown
        default: op
commands:
   gh:
      description: GH GIVE gives a grappling hook.
      usage: /<command>
